### ISSUE TITLE
Request for documentation on how to get a PWB licence for a new start

### ISSUE THREAD

**Issue by elizabeth-richardson** [Public-Health-Scotland/knowledge-base#37]
The Knowledge Base has good info on how to use Posit, but not on how to get a licence initially. Can the process be documented please?

**Comment by rmccreath** [comment]
Content requests related to documentation (i.e. guidance) for the Knowledge Base should be made on the [technical-docs](https://github.com/Public-Health-Scotland/technical-docs) repo. However, I believe this request has now been covered already: https://public-health-scotland.github.io/knowledge-base/docs/Posit%20Infrastructure?doc=How%20to%20Access%20Posit%20Workbench.md
